
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { Navbar } from "./components/navbar";
import MobileNav from "./components/mobileNavbar";
import CallMe from "./components/callMe";
import Footer from "./components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next"

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})


export const metadata: Metadata = {
  title: "Ace Plumbing Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <Navbar />
        <MobileNav />
        <div className="2xl:px-44">
        <SpeedInsights />
        <CallMe />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}
